- docs/mpz.rst
- src/gmpy2_mpz_misc.c
Signed-off-by: mulhern <amulhern@redhat.com>
> Fix typo: denominator -> divisor

- setup.py
- test_cython/runtests.py
- test_cython/setup_cython.py
- test_cython/test_cython.pyx
This PR fixes header installation (only installs gmpy2.h) and provides a testsuite for Cython.
> Cython testsuite

- .appveyor.yml
- .travis.yml
- test/test_mpfr_trig.txt
If you want to test other python versions, let me know
> Continuous Integration with Travis-CI and appveyor

- src/gmpy2.pxd
- test_cython/test_cython.pyx
adding mpfr declarations in pxd + appropriate tests
> mpfr in pxd

- src/gmpy2.pxd
- test_cython/test_cython.pyx
> GMPy_MPFR_From_mpfr and more cython tests

- src/gmpy2.pxd
- test/test_gmpy2_constructors.txt
- test_cython/test_cython.pyx
related to #146
- new mpc cython test added in test_cython.pyx
- mpc tests in test_gmpy2_constructors.txt
- new exception raising cases added in test_gmpy2_constructors.txt
> add mpc integration in gmpy2.pyd

- docs/cython.rst
- docs/index.rst
Add documentation for C-API and Cython
> documentation for Cython

- docs/cython.rst
- src/gmpy2.pxd
- test_cython/runtests.py
- test_cython/test_cython.pyx
Great simplifications of the Cython interface after a discussion that happened at
https://groups.google.com/forum/#!topic/cython-users/XQX1UpFup8c
> cleaner Cython interface

- .travis.yml
Provide a straightforward travis script to test under Ubuntu. The miniconda version is discarded for now.
The tests do pass: https://travis-ci.org/videlec/gmpy/builds/268387544
> add travis script

- .travis.yml
- docs/Makefile
Small pull request to also test doc building (both html and pdf) in travis CI.
> Doc in travis

- src/gmpy2.pxd
Minor improvements to Cython declarations.
> Improve Cython declarations

- test_cython/test_cython.pyx
adapt test to the new cython interface (PR #169)
> test_cython.pyx : Fix issue #170

- gmpy2/__init__.pxd
- gmpy2/__init__.py
Correct fix for #189. Replaces #190
> Fix cython C-API imports.

- src/gmpy2_mpz_inplace.c
> Fix mpz += 0 setting the value to a random number.

- scripts/setup.py
> add one missing comma

- scripts/setup.py
This fixes the last alerts found by lgtm.
> remove 2 unused imports and comment 2 unused lines

- src/gmpy2_convert.h
A lot of compilation warning have been introduced by #217. This simple PR fix that.
> Simple fix to remove a lot of compilation warnings

- .github/workflows/pip_install_gmpy2.yml
Passes on macOS but fails on Linux and Windows  https://github.com/cclauss/gmpy/actions
> GitHub Action to pip install gmpy2 on multiple OSes and Python versions

- .github/workflows/build_wheels.yml
- scripts/before_ci_build.sh
> Add wheels for unix and macOS

- docs/cython.rst
Two files were swapped in the docs
Reviewer @aleaxit
> Docs: Fix Cython File Order

- .github/workflows/pip_install_gmpy2.yml
- setup-legacy.py
- setup_msys.py
- src/gmpy2.c
@casevh, this should fix CI failure.
> Correct CI failure on the master branch

- .github/workflows/build_wheels_apple_silicon.yml
- scripts/before_ci_build_apple_silicon.sh
I've test on my MacBook and it works.
Here are the wheels: https://github.com/bebound/gmpy/actions/runs/1621969439
```
Unit tests for gmpy2 2.1.1 with Python 3.9.9
Mutliple-precision library:     GMP 6.2.1
Floating-point library:         MPFR 4.1.0
Complex library:                MPC 1.2.1
Caching Values: (Cache size)    100
Caching Values: (Size in limbs) 128
Results for:  test_context              Attempted:   38   Failed:    0
Results for:  test_gmpy2_abs            Attempted:   83   Failed:    0
Results for:  test_gmpy2_add            Attempted:   82   Failed:    0
Results for:  test_gmpy2_binary         Attempted:  106   Failed:    0
Results for:  test_gmpy2_cmp            Attempted:   41   Failed:    0
Results for:  test_gmpy2_comp           Attempted:   89   Failed:    0
Results …
```
> Add apple silicon wheels

- test/gmpy_test.py
…which was removed in 87008be5
> Remove mention of the old test suite

- docs/mpfr.rst
- src/gmpy2_math.c
floor is the largest integer <= x
> minor doc typo

- .github/workflows/pip_install_gmpy2.yml
- README.rst
- docs/conf.py
- docs/mpz.rst
- docs/win_build.rst
- pyproject.toml
* README -> README.rst
* fix description for some instance attributes
* remove redundant/useless sphinx directives
* fix sphinx warning for docs/win_build.rst
* enable docs building in GA
* Use sphinx_rtd_theme for local builds too
> Minor fixes for docs

- .github/workflows/pip_install_gmpy2.yml
- pyproject.toml
- test_cython/setup_cython.py
See cython/cython#5232 for the PYTHONPATH workaround.
> Test cython integration in the pip_install_gmpy2.yml workflow

- README.rst
> Restore README.rst (broken in 26519fa)

- demo/gmpy2_demo.c
- src/gmpy2_add.c
- src/gmpy2_cache.c
- src/gmpy2_convert_gmp.c
- src/gmpy2_convert_gmp.h
- src/gmpy2_convert_mpc.c
- src/gmpy2_convert_mpc.h
- src/gmpy2_convert_mpfr.c
- src/gmpy2_convert_mpfr.h
- src/gmpy2_convert_utils.h
- src/gmpy2_divmod.c
- src/gmpy2_floordiv.c
- src/gmpy2_mod.c
- src/gmpy2_mpmath.c
- src/gmpy2_mpz_bitops.c
- src/gmpy2_mpz_misc.c
- src/gmpy2_mpz_misc.h
- src/gmpy2_mul.c
- src/gmpy2_richcompare.c
- src/gmpy2_sub.c
- src/gmpy2_xmpz_inplace.c
- src/gmpy2_xmpz_misc.c
- src/gmpy2_xmpz_misc.h
- src/mpz_pylong.c
- test/test_mpz_functions.txt
Mostly PyIntOrLong -> PyLong renaming.
> Cleanup for older python versions

- src/gmpy2_mpz.c
- src/gmpy2_mpz_misc.c
- src/gmpy2_mpz_misc.h
- test/test_gmpy2_mpz_misc.txt
> Add mpz.as_integer_ratio()

- .github/workflows/pip_install_gmpy2.yml
- src/gmpy2_convert_gmp.c
This also enables basic testing on 3.12.
> Add compatibility macro to work with CPython 3.12 internals too

- src/gmpy2_convert.c
- src/gmpy2_convert_gmp.c
- src/gmpy2_convert_mpc.c
- src/gmpy2_convert_mpfr.c
- test/test_mpz_create.txt
> Fix incompatible (c.f. int) initialization of mpz from strings

- docs/advmpz.rst
- docs/conf.py
- docs/contexts.rst
- docs/conversion.rst
- docs/cython.rst
- docs/mpc.rst
- docs/mpfr.rst
- docs/mpq.rst
- docs/mpz.rst
- docs/overview.rst
- src/gmpy2_binary.c
- src/gmpy2_context.c
- src/gmpy2_divmod.c
- src/gmpy2_format.c
- src/gmpy2_math.c
- src/gmpy2_mod.c
- src/gmpy2_mpfr_misc.c
- src/gmpy2_mpq_misc.c
- src/gmpy2_mpz_bitops.c
- src/gmpy2_mpz_misc.c
- src/gmpy2_muldiv_2exp.c
- src/gmpy2_pow.c
- src/gmpy2_predicate.c
- src/gmpy2_square.c
- src/gmpy2_xmpz_limbs.c
- src/gmpy2_xmpz_misc.c
- src/gmpy_mpz_prp.c
- added autodoc_default_options sphinx directive
- added nitpicky sphinx directive (test for broken references)
- amended c10ebcb (gmpy2._context -> gmpy2.context)
- sphinx's default_role used to add cross-references to gmpy2/python objects/functions/classes
- more simple function signature for round2()
- exceptions added to the sphinx docs (no docstrings yet)
> Minor changes for docs

- .github/workflows/pip_install_gmpy2.yml
This is fast, so lets test this os too.  BTW, there are some compiler warnings.
No wheels yet.
> Run tests on the windows-latest too

- src/gmpy2_convert.h
- src/gmpy2_convert_gmp.c
- src/gmpy2_convert_utils.c
Fixes #405
Also do some code reorganization.
> Adapt conversion utils for the CPython 3.12.0a7+

- pyproject.toml
- src/gmpy2.c
- src/gmpy2_mpfr.c
- src/gmpy2_mpfr_misc.c
- src/gmpy2_mpfr_misc.h
- src/gmpy2_mpmath.c
- test/test_mpfr.py
Closes https://github.com/aleaxit/gmpy/issues/353
> Implement mpfr._mpf_ property (mpmath integration)

- docs/conversion.rst
- docs/history.rst
- docs/index.rst
- docs/intro.rst
- docs/mpfr.rst
- docs/mpz.rst
- docs/overview.rst
- src/gmpy2_mpz_pack.c
* add mpfr_nrandom(), pack() and unpack() to sphinx docs
* fix formatting & add refs to history.rst
* update docs/intro.rst & versions info
* adapt some headers in prose docs
> Misc fixes

- scripts/before_ci_build.sh
- scripts/before_ci_build_apple_silicon.sh
- src/gmpy2_format.c
Closes https://github.com/aleaxit/gmpy/issues/418
> Update MPFR to 4.2.1 in build scripts & fix test failures on new version

- src/gmpy_mpz_prp.c
See e.g.
https://en.wikipedia.org/wiki/Solovay%E2%80%93Strassen_primality_test
Closes #427
> Amend is_euler_prp() docstring

- docs/conf.py
- docs/mpz.rst
> Include prev_prime() to the sphinx docs unconditionaly

- .github/workflows/pip_install_gmpy2.yml
Should fix the build failure in the current master.
> Do apt-get update for linux job

- src/gmpy2_convert_gmp.c
- src/gmpy2_format.c
> Fix compiler warnings on Windows 2022 with msys2

- src/gmpy2_xmpz.c
> Add xmpz.bit_count()

- src/gmpy2_convert_mpfr.c
- test/test_mpfr.py
> Fix creating of mpfr's with base=0 for negative values

- src/gmpy2_convert_gmp.c
- src/gmpy2_convert_mpfr.c
- test/test_mpfr.py
- test/test_mpq.py
- test/test_mpz.py
> Fix mpz/mpq.__float__, add tests

- src/gmpy2_divmod.c
- src/gmpy2_floordiv.c
- src/gmpy2_truediv.c
- test/test_mpfr.py
> Pass context arguments to division functions

- .github/workflows/build_wheels.yml
- pyproject.toml
- src/gmpy2.c
- src/gmpy2_context.c
> Update cibuildwheel & add PyPy wheels

- src/gmpy2_mpq.c
- src/gmpy2_mpq_misc.c
- src/gmpy2_mpz.c
- src/gmpy2_mpz_misc.c
- test/test_mpq.py
- test/test_mpz.py
> Add is_integer() method for mpz/mpq types

- pyproject.toml
That fix SetuptoolsDeprecationWarning.
> Use SPDX license value

- src/gmpy2_add.c
- src/gmpy2_mul.c
- src/gmpy2_sub.c
- src/gmpy2_truediv.c
- test/test_mpc.py
> Support mixed-mode arithmetic for mpc

- src/gmpy2_format.c
- test/test_mpc.py
- test/test_mpfr.py
> Use context's rounding mode per default in format()

- .github/workflows/build_wheels.yml
> Build wheels for Linux ARM
