docs/mpfr.rst, docs/mpz.rst, src/gmpy2_mpz_misc.c
These typos were found and reported by Lintian in the Debian packaging
for gmpy. This patch fixes them.  Although these are not super
important, they will make it easier to see real warnings/issues with
a cleaner Lintian page.
Here's the relevant Lintian page:
https://lintian.debian.org/full/martin@martingkelly.com.html
=> trivial: spelling fixes

src/gmpy2_cache.c
This would allow any object to implement their own conversion to gmpy2. The branch just make `gmpy2.mpz(a)` so that it calls `a.__mpz__()` when the method exists (and similar for `mpq`). With the branch applied one can do
>>> class A:
...    def __mpz__(self):
...        import gmpy2
...        return gmpy2.mpz('42')
...    def __mpq__(self):
...        import gmpy2
...        return gmpy2.mpq('13/12')
>>> import gmpy2
>>> gmpy2.mpq(A())
mpq(13,12)
>>> gmpy2.mpz(A())
mpz(42)
(fixes issue #123)
=> check for __mpz__ and __mpq__ in New

setup.py, src/gmpy2.pxd
We have successfully tested the PR with our [pplpy](https://github.com/videlec/pplpy/) project. Sage integration is on its way.
You might want to add public interface to mpfr/mpc (see the TODO in `gmpy2.pxd` in commit b805459)
=> basic gmpy2.pxd and custom setup.py to install headers

src/gmpy2.pxd, test_cython/runtests.py, test_cython/test_cython.pyx
- add type checkers in gmpy.pxd
- add some tests in cython test suite
- Fix a bug, causing runtest.py to crash
if called from test_cython directory
related to issue #139
=> add type checkers in gmpy.pxd

src/gmpy2.pxd, test_cython/test_cython.pyx
The following command in Cython
py_obj = <object> my_py_obj
increases the reference counter of my_py_obj. As a consequence the following code gets wrong refcount
res = <object> GMPy_MPZ_New(NULL)
and the object `res` will never be deallocated by the garbage collector.
=> fix and tests Cython memory leak

README
According to [this](https://github.com/aleaxit/gmpy/blob/c9e086e16d040d86a955900e4cd7593dadfab3f1/setup.py#L208) it's the "--shared" parameter what counts, not "--prefix". 
At least that was the reason I wasn't able to install the package.
=> Change --prefix to --shared in the README

src/gmpy2.pxd
- a comment was wrong
- declarations of `mpc_prec_t` where completely wrong (I do not even understand by which miracle this has worked before)
=> tiny fixes to Cython file

docs/mpz.rst
The documentation for function/method "bit_set" is incorrectly portraying that the n-th bit would be changed to 0, while in fact it changes this bit to 1.
=> Corrected bit_set description

src/gmpy2_floordiv.c, test/test_mpq.txt
- Fix this bug. Appear when one of the parameters are not an MPQ (PyLong or MPZ for exemple).
- Add two test for these cases. 
- Fix needed for issue #146
=> Bug fix : mpq floor division #156

src/gmpy2_convert_utils.c, src/gmpy2_mpmath.c, src/gmpy2_pow.c
Add explicit cast to silence warnings on win64 platform.
For the four case in files gmpy2_convert_utils.c and gmpy2_convert_utils.c(195) where overflow are implossible. 
Issue #146
=> Add explicit cast to silence warnings on win64 platform

.travis.yml, test/test_mpfr_trig.txt
rewrite test_mpfr_trig:  mpmath is platform dependent and using it cause error with osx like in this build "https://travis-ci.org/vinklein/gmpy/jobs/297897566". These errors appear in issue #163 too.
Doctest on osx works with this version (https://travis-ci.org/vinklein/gmpy/jobs/298538269).
travis.yml: Rework the file to have osx tests running correctly (cython and make docs). 
Linked to issue #157.
still to fix : make "make latexpdf" command work on osx
=> Fix travis.yml and test_mpfr_trig for osx.

src/gmpy2_cache.c, test/test_gmpy2_constructors.txt
issue #173 
- Fix segfault when objects have custom `__mpz__`, `__mpq__`,
`__mpfr__` or `__mpc__` methods raising errors.
- add doctests for these cases.
=> gmpy2_cache.c : Fix issue #173

src/gmpy2_mpc_misc.c, test/test_mpc.txt
Fix for issue #179 
- .real and .imag mpfr now return the same precision as their mpc
- add doctests for these cases.
=> Fix for mpc precision inconsistency issue #179

src/gmpy2.pxd
Allow accessing the internals of the various types.
Second, by doing this, the function `GMPy_MPC_From_mpfr` can be used without linking against the MPC library (by replacing the `mpc_set_fr_fr` call by two `mpfr_set` calls). This makes sense because the function takes `mpfr_t` as input. So it's reasonable to expect linking against MPFR.
=> Add data structures for the various types

src/gmpy2.pxd
The type `mpfr_prec_t` is declared twice (identically) by mistake.
=> Remove duplicate declaration of mpfr_prec_t

.travis.yml
With previous travis.yml cython was not detected by
test_cython/runtests.py and then no cython tests executed
=> .travis.yml install a newer version of cython

.travis.yml
Trusty support will end next month.
Using xenial for test also fix issue #213
=> travis.yml: Use xenial instead of trusty for  linux tests.

docs/conversion.rst, docs/index.rst, src/gmpy2_cache.c, src/gmpy2_convert.h, src/gmpy2_convert_gmp.c, src/gmpy2_convert_mpc.c, src/gmpy2_convert_mpfr.c, test/test_gmpy2_add.txt, test/test_gmpy2_mul.txt, test/test_gmpy2_sub.txt, test/test_mpc.txt, test/test_mpfr.txt, test/test_mpq.txt, test/test_mpz.txt
Fix issue #214
Allow arithmetic operations between gmpy2 numbers and objects with custom __mpz__, __mpq__, __mpfr__ or __mpc__ methods.
Add tests and documentation (conversion.rst).
This branch pass travis-ci test if merged with PR #216. (see https://travis-ci.org/vinklein/gmpy/builds/502597870)
=> Fix issue #214 Allow arithmetic operation between gmpy2 numbers and custom objects

src/gmpy2_mpz_bitops.c, test/test_gmpy2_convert.txt, test/test_gmpy2_mpz_bitops.txt
Issue #222 :
- Fix core dump bug in scanf0, scanf1 and bit_test functions
- Fix GMPy_MPZ_bit_flip_function always return error
- Fix an error message.
Add tests for gmpy2_mpz_bitops functions and methods. (see #199)
=> Fix issue #222 and add tests for gmpy2_mpz_bitops

src/gmpy2_math.c, test/test_gmpy2_math.txt
Fix gmpy2's round2 segfault when this function is called with one parameter.
- Use context default precision for mpfr instead of 0.
- Add few tests for round2.
=> Fix issue #226 gmpy2's round2 segfault

src/gmpy2_mpc_misc.h, test/runtests.py, test/test_mpc.txt
Currently if gmpy2 is used with a mpc version older than 1.1.0 it generate a compilation warning and doctests failures as `gmpy2.root_of_unity` attribute is not defined.
```
Example of doctests failures :
Failed example:
gmpy2.root_of_unity(1,2)
Exception raised:
Traceback (most recent call last):
File "/opt/python/3.5.6/lib/python3.5/doctest.py", line 1321, in __run
compileflags, 1), test.globs)
File "<doctest test_mpc.txt[114]>", line 1, in <module>
gmpy2.root_of_unity(1,2)
AttributeError: module 'gmpy2' has no attribute 'root_of_unity'
```
see: https://travis-ci.org/vinklein/gmpy/builds/509298994
- Fix `gmpy2_mpc_misc.h` to avoid generating warning
- Create a doctest flag and a doctest parser to SKIP doctests if `root_of_unity` is not defined
- Flag the appropriate doctests
=> Fix root_of_unity warning and doctests errors. When mpc version != 1.0.0

test/test_gmpy2_floordiv.txt, test/test_gmpy2_muldiv_2exp.txt, test/test_mpc.txt, test/test_mpfr.txt, test/test_mpq.txt, test/test_mpz.txt
This PR is part of issue #199 
Add doctests for functions defined in files below :
- gmpy2_floordiv.c
- gmpy2_muldiv_2exp.c
- gmpy2_truediv.c
- gmpy2_mod.c
- gmpy2_sign.c
Regarding test coverage, this PR give 80.8 % line coverage and 87.8 % of function coverage
=> Add doctests for several files

src/gmpy2_convert.c, test/test_gmpy2_format.txt
calling digits (mpz, xmpz or mpq) method with a base of 0 used to
generate a core dump.
Ex:
>>> from gmpy2 import mpq
>>> q = mpq(2,5)
>>> q.digits(0)
Floating point exception (core dumped)
- Fix mpz_ascii function.
- Add some doctests to ensure these bugs are fixed.
=> Fix mpz_ascii function : core dump when parameter base=0.

src/gmpy2_cache.c, test/test_gmpy2_constructors.txt
- In mpq init replace `GMPy_MPQ_From_Rational` call by `GMPy_MPQ_From_Number`.
- Add few doctests.
The ubuntu travis-ci doctests failures are fixed by PR #239
=> Fix issue #237 allow to use a pair of objects defining __mpz__  to initialize an mpq.

src/gmpy2_cmp.c, test/runtests.py, test/test_gmpy2_cmp.txt, test/test_mpc.txt
Fix issue #238:
- Avoid to call `mpc_cmp_abs` function when mpc version is lesser than 1.1.0.
- Adapt doctest accordingly.
=> Issue #238: Fix unreconized mpc_cmp_abs symbol

src/gmpy2_mpq_misc.c, test/test_gmpy2_mpq_misc.txt, test/test_mpq.txt
Two tests were altered.  Apparently, they were wrong:
before lines "gmpy2.qdiv(10, q)" and "q.__round__(4)" - q was
changed by previous calls to 2/5.
Closes aleaxit/gmpy#242
PS: Probably you could enable travis-ci for this repo and pull requests.  Anyway, this commit pass your CI tests, see [here](https://travis-ci.org/skirpichev/gmpy/builds/537415585), regression test was added.
=> Fix mutation in the first argument of qdiv()

src/gmpy2.c, src/mpz_pylong.c
Currently, src/gmpy2.c is ISO8859-1.  I don't recognize the encoding of mpz_pylong.c.  It might be doubly encoded.  In any case, this commit changes them both to Unicode.
=> Convert C file character encodings to UTF-8.

docs/mpz.rst
I used
`grep --color -nriP '([^r]fac(?!(tor|ili|ts|tur))|primorial)' .`
to make sure that fac/doublefac/multifact/primorial appear in the same files
=> Documentation for double_fac, multi_fac, primorial

src/gmpy2.c, src/gmpy2.h, src/gmpy2_xmpz.c, src/gmpy2_xmpz_limbs.c, src/gmpy2_xmpz_limbs.h, test/test_gmpy2_xmpz_limbs.txt
This PR exposes the `mpz_limbs` [interface](https://gmplib.org/manual/Integer-Special-Functions.html) through 5 new methods on `xmpz` to provide access to the backing storage of an `xmpz` object. This is for fast access to the `gmp` internals to perform quick compression/decompression of the underlying `mpz` data.
Methods added:
- `xmpz.num_limbs() -> int`
returns the number of `gmp` limbs underlying this `xmpz` object
- `xmpz.limbs_read() -> int`
returns the address of an immutable buffer representing the limbs of `xmpz`
- `xmpz.limbs_write(n) -> int`
potentially reallocates and returns the address of a mutable buffer representing the limbs of `xmpz`, sized to hold at least `n` limbs. May overwrite the existing limbs of `xmpz`.
- `xmpz.limbs_modify(n) -> int`
potentially reallocates and …
=> Add access to gmp limbs API

.travis.yml
The `sudo` and `matrix` tags are deprecated in Travis CI.  Add tests against current versions of Python.  Output at https://travis-ci.com/github/cclauss/gmpy
=> Travis CI: Simplify with most repeated defaults

src/gmpy2.h, src/gmpy2_mpmath.c
This is one approach that could be taken to resolve https://github.com/aleaxit/gmpy/issues/276.  It works for python 3.8 and 3.9, at least.  My reading of the docs suggests that it might work for versions as old as 3.3, but I haven't tested anything older than 3.8.
=> Correctly read rounding mode strings when characters are multibyte

src/gmpy2_convert_gmp.c, test/runtests.py
The Fedora distribution has started doing experimental builds with alpha versions of python 3.10, to discover and fix problems in advance of the 3.10 release.  The gmpy code has 2 issues.  First, Py_SIZE() is no longer an lvalue in 3.10.  A Py_SET_SIZE macro was introduced in 3.9 in anticipation of this change; its use is mandatory in 3.10.  The second issue is test code that checks whether the python version string starts with "3.1"; that is true of 3.10 also, of course.  Since setup.py claims support only for 3.4 and later, it may be better to simply remove that entire block of code.  Let me know if you prefer that and I will update this commit.
=> Python 3.10 compatibility.

src/gmpy2.h, src/gmpy2_add.c, src/gmpy2_context.c, src/gmpy2_context.h, src/gmpy2_divmod.c, src/gmpy2_floordiv.c, src/gmpy2_mul.c, test/test_context.txt, test/test_mpc_create.txt, test/test_mpfr_create.txt, test/test_mpfr_trig.txt
As discussed in #291 this allows threads during certain MPZ operations.  The choice is made based on a new flag in the context structure, but not on the characteristics (size) of the numbers involved.
Testing performed:
* built on Linux with Python 3.7.3
* Ran `tests/runtests` (some expected output updated)
* Ran my [fib programs](https://gist.github.com/f3566b4d9222fd29839f1260bbcc0b01), comparing threaded and unthreaded performance in the range where threads are a benefit:
```
$ time python3 fib6.py $((1<<27))  # Threads enabled
134217728: 28049846 digits: 803430834915283969401079…337223560039659570859461
real	0m1.749s
user	0m6.196s
sys	0m0.411s
$ time python3 fib5.py $((1<<27)) # Threads disabled
134217728: 28049846 digits: 803430834915283969401079…337223560039659570859461
real …
```
=> Allow threads in certain mpz operations, subject to a flag

src/gmpy2_hash.c
In python 3.10 _PyHASH_NAN was removed and its usage replaced with _Py_HashPointer.
see https://github.com/python/cpython/blob/3.10/Python/pyhash.c#L102
=> Use _Py_HashPointer for python 3.10

.github/workflows/build_wheels.yml, scripts/before_ci_build.sh
- bump `cibuildwheel` to the latest version
- Use `.xz` for `GMP` tarball, otherwise some docker images used by `cibuildwheel` don't have good enough tar.
- use `curl` for downloading, it's everywhere, no need to install it (this installation fails on an `i686` docker image).
- Do not skip  `musllinux` (aka `linux-musl`) in the pre-build script.
This gives us
```
gmpy2-2.1.0rc2-cp310-cp310-macosx_10_9_x86_64.whl
gmpy2-2.1.0rc2-cp310-cp310-manylinux_2_17_i686.manylinux2014_i686.whl
gmpy2-2.1.0rc2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
gmpy2-2.1.0rc2-cp310-cp310-musllinux_1_1_i686.whl
gmpy2-2.1.0rc2-cp310-cp310-musllinux_1_1_x86_64.whl
gmpy2-2.1.0rc2-cp36-cp36m-macosx_10_9_x86_64.whl
gmpy2-2.1.0rc2-cp36-cp36m-manylinux_2_17_i686.manylinux2014_i686.whl …
```
=> latest cibuildwheel, curl, not wget, xz, not lz, and wheels for musllinux

setup.py
The code uses log() which requires this library, but it relied on
Python's own link to this library to resolve the symbol. Making the
requirement explicit is not only more clear, but prevents GNU ld's
--no-undefined option from complaining.
=> Explicitly link against libm

.github/workflows/build_wheels.yml, scripts/before_ci_build.sh, scripts/before_ci_build_apple_silicon.sh
That reverts part of erroneously merged #361.  No testing for cython integration for wheels yet.
@bebound I'll appreciate your review (wheels testing doesn't work yet on the macos arm64 builds).  For some reason delocate was unable for fix arm64 wheels in #361 or https://github.com/skirpichev/gmpy/tree/fix-arm64.  Now everything was reverted to the previous setup and library files are included in wheels.  It would be nice if we can leave comments on variables in the scripts/before_ci_build_apple_silicon.sh (e.g. LDFLAGS seems to be redundant, as there is ARCHFLAGS).
=> Revert part of #361 related to arm64 builds (now a separate job again)

scripts/before_ci_build.sh, scripts/before_ci_build_apple_silicon.sh
An example:
https://github.com/aleaxit/gmpy/actions/runs/4060983530/jobs/6990590195
It's not clear what's was failing: curl (probably it is and --retry option may be useful) or tar.
Cleanup some debugging echo/set calls.
=> Enable printing command input lines in scripts/before*.sh

.github/workflows/pip_install_gmpy2.yml, test/test_gmpy2_mpz_misc.txt, test/test_mpz.txt
* genhtml output stored in the build artifact
* few new coverage tests (seems to be correct, but please check)
* upload coverage results to the codecov.io (that, probably, needs some configuration on your side)
=> Enable coverage testing in CI

docs/contexts.rst, gmpy2/__init__.py, src/gmpy2.c, src/gmpy2_context.c, src/gmpy2_context.h
Private _context type was exported in 1b05503 just to show context methods/attributes in docs.
=> Expose context type (was _context) as context (was a function)

.github/workflows/build_wheels.yml, .github/workflows/pip_install_gmpy2.yml, .gitignore, pyproject.toml, src/gmpy2_mpz.c, src/gmpy2_mpz_misc.c, src/gmpy2_mpz_misc.h, test/runtests.py, test/test_mpz.py
Closes #357
Some benchmarks:
```
$ python -m timeit -s 'from math import factorial' -s 'a = factorial(57)' 'a.to_bytes(32)'
500000 loops, best of 5: 285 nsec per loop
$ python -m timeit -s 'from gmpy2 import fac' -s 'a = fac(57)' 'a.to_bytes(32)'
500000 loops, best of 5: 486 nsec per loop
$ python -m timeit -s 'from gmpy2 import fac' -s 'a = fac(57)' 'int(a).to_bytes(32)'
500000 loops, best of 5: 823 nsec per loop
```
It seems, int.to_bytes() is slightly better than the mpz_export.
I don't know which formatting should be used for the C code, so PEP 7 is used.  Let me know if I shouldn't use braces for single-line if/for statements or something else.  
BTW, this PR adds an optional dependency on [pytest](https://pytest.org/) and [hypothesis](https://hypothesis.readthedocs.io/), so added …
=> Add mpz.to_bytes()/from_bytes()

src/gmpy2_mpz_misc.c
a fix from the [review comment](https://github.com/aleaxit/gmpy/pull/394#issuecomment-1465314664) of #394
=> Amend f76c420 (avoid TEMP_ALLOC)

test/conftest.py
I believe this should fix random failures like [this](https://github.com/aleaxit/gmpy/actions/runs/4943181612/jobs/8837416087).
=> pytest: add fixture to reset the current context to defaults

src/gmpy2_convert.h, test/conftest.py, test/test_mpz.py
This fix int(mpz(0)) for CPython versions < 3.12
=> Amend b2236fc

docs/conf.py, docs/history.rst, docs/mpz.rst, src/gmpy2.c, src/gmpy2_mpz_misc.c, src/gmpy2_mpz_misc.h, test/test_gmpy2_mpz_misc.txt, test/test_mpz.py, test/test_mpz_functions.txt
I authored `mpz_prevprime` and finally got it upstreamed. I'd love if gmpy2 would also support this (as I mostly call gmp via your wonderful wrapper).
Couple of notes
* I throw `Py_RETURN_NOTIMPLEMENTED` if `__GNU_MP_VERSION < 6.3`
I'm not sure when gmp 6.3 release will happen but this is the safest option. I/you/others can always remove this line (or change it to 6.2) when using development version of the repo which uses build version 6.2.99.
* mpz_prevprime has an int return (0 when no previous prime (arg < 2), definite prime, probable prime) I can return a two element tuple but IMHO it's better to just return the previous_prime (or 2).
=> Added prev_prime(x)

pyproject.toml
Removing `pip` and `wheel`, which are not needed.
(for wheel, see https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use)
=> pyproject.toml: Update [build-system] requires

test/test_mpfr.py
Since gmpy2 is a build dependency for mpmath, this allows testing gmpy2 before mpmath is built.
=> Skip mpmath test if module not available

docs/conf.py, gmpy2/__init__.py, src/gmpy2.c
This is a more standard way to embed version info.  Recognized, e.g. by pytest.importorskip.  
Also, simplify version handling in docs/conf.py.
Probably, we could also deprecate gmpy2.version() function.  @casevh, what do you think?
=> Add __version__ module attribute

.github/workflows/pip_install_gmpy2.yml, src/gmpy2_convert.h, src/gmpy2_hash.c
Turn on basic tests on 3.13
Closes #417
=> CPython 3.13: add _PyLong_New() and import some macros from pycore_hash.h

scripts/before_ci_build.sh
Fixes https://github.com/aleaxit/gmpy/issues/438
cc @skirpichev
=> Fix microarchitecture specific code in common code paths

.github/workflows/pip_install_gmpy2.yml, src/gmpy2_hash.c, test/conftest.py, test_cython/runtests.py
9fce264 Don't use private API: _Py_HashPointer
1de1bc2 Add workaround for shutil.copytree on CPython 3.7
2b805ac Run Cython tests in coverage job
b723d71 Run _set_default_context() fixture per function
ac2cfe2 Add pytest_report_header(), like test/runtests.py
=> Misc fixes

src/gmpy2_hash.c
Also drop some inaccessible code in GMPy_MPC_Hash_Slot()
-----
This is cherry-picked from #452.  Old discussion: https://github.com/aleaxit/gmpy/commit/324e284037a334bf9523ffcf508efe3a854706c4#commitcomment-131773663
=> Fix compiler warning in _mpfr_hash()

src/gmpy2_convert_utils.c, src/gmpy2_convert_utils.h, src/gmpy2_mpz_misc.c, src/gmpy2_muldiv_2exp.c, test/test_functions.py, test/test_generic.py
* We try to convert to unsigned long (for mpfr_mul_2ui) and fallback to long on overflow (for mpfr_mul_2si), closes #328
* Add GMPy_Integer_AsUnsignedLongOrLong() and adapt div_2exp() like above
* Return OverflowError in iroot(x,n) iff n>ULONG_MAX, closes https://github.com/aleaxit/gmpy/issues/257
=> Support negative exponents in mul_2exp

.github/workflows/build_wheels.yml, scripts/before_ci_build.sh, scripts/before_ci_build_apple_silicon.sh, scripts/repair_ci_wheel.sh, test_cython/setup_cython.py, test_cython/test_cython.pyx
=> Run Cython tests for binary wheels

.github/workflows/build_wheels.yml, .github/workflows/build_wheels_legacy.yml, .github/workflows/pip_install_gmpy2.yml, scripts/before_ci_build.sh, scripts/before_ci_build_apple_silicon.sh, src/gmpy2_cache.c, src/gmpy2_format.c
28c81b8 Update versions for runners in CI
af43dc6 Enable pip_install_gmpy2.yml for push/pr (it's cheap!)
fec75d2 Use ftp.gnu.org for GMP download
c57464b Exclude MPFR workaround for MPFR >= 4.2.1
4cecd73 Additional patch from aleaxit/gmpy#418
=> Fix CI on gmpy2-2.1.6 branch

src/gmpy2_convert_gmp.c, test/test_mpz.py
@casevh, that solves issue, mentioned in #483.  But this code should be benchmarked.
=> Update int <-> mpz conversion

.github/workflows/pip_install_gmpy2.yml
It seems, https://app.codecov.io/gh/aleaxit/gmpy - not updating. And coverage for new pull requests is missing too:
https://app.codecov.io/gh/aleaxit/gmpy/pulls?prStates%5B0%5D=OPEN
This update codecov-action version and add fail_ci_if_error option to prevent CI failures on the master.  In this form, submitting data works in mpmath's prs.
If someone menages to add CODECOV_TOKEN (as it's explained in https://github.com/codecov/codecov-action/?tab=readme-ov-file#usage)
- then we could remove fail_ci_if_error option (defaults to true).
=> Use codecov-action v4

src/gmpy2_convert.c, src/gmpy2_mpz_misc.c
I attempted to build version 2.2.0 for Fedora Rawhide.  All of the non-x86 architectures (aarch, ppc64le, and s390x) failed a test:
```
=================================== FAILURES ===================================
_____________________________ test_mpz_from_bytes ______________________________
@settings(max_examples=1000)
>   @given(integers(), integers(min_value=0, max_value=10000),
sampled_from(['big', 'little']), booleans())
test/test_mpz.py:108: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.13/site-packages/hypothesis/core.py:1300: in _raise_to_user
raise the_error_hypothesis_found
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
x = -2, length = 5, byteorder = 'little', signed = True …
```
=> Use int instead of char for flag variables

src/gmpy2_context.c
Simple manpage typos found by Lintian as part of the Debian packaging process.
=> Fix manpage typos

src/gmpy2_cache.c
=> Fix memory leak for mpfr/mpc cache (amend 7351e2e)

src/gmpy2.c
Since 6.3.0 some memory errors in mpz/realloc.c trigger SIGFPE exception.  I think it's an upstream bug: helpful message should be emitted instead.
This patch install SIGFPE handler, that does this.
Closes #497
=> Add signal handler to catch SIGFPE on the GMP 6.3+

pyproject.toml, src/gmpy2_mpz.c, src/gmpy2_mpz_misc.c, src/gmpy2_mpz_misc.h, test/test_mpz.py
=> Add mpz.__array__() method to interact with numpy

src/gmpy2_context.c
=> Fix memory leak in GMPy_CTXT_Exit()

.github/workflows/build_wheels.yml, .github/workflows/pip_install_gmpy2.yml, src/gmpy2_add.c, src/gmpy2_convert_gmp.c, src/gmpy2_divmod.c, src/gmpy2_floordiv.c, src/gmpy2_mod.c, src/gmpy2_mul.c, src/gmpy2_richcompare.c, src/gmpy2_sub.c, src/gmpy2_xmpz_inplace.c
The PEP 757 is accepted.  This pr factor out required changes in the mpz_set_PyLong() signature to make #495.  Once merged, I'll rebase mentioned pr.
=> Update mpz_set_PyLong() signature (return an integer)

src/gmpy2.c, src/gmpy2_convert.h, src/gmpy2_convert_gmp.c, src/pythoncapi_compat.h
=> Use PEP 757 C-API to import/export ints 

src/gmpy2_format.c
Closes https://github.com/aleaxit/gmpy/issues/522
See https://github.com/aleaxit/gmpy/issues/522#issuecomment-2431541545
=> Prevent crash in GMPy_MPFR_Format()

src/gmpy2_cache.c, test/test_mpc.py, test/test_mpfr.py, test/test_mpq.py, test/test_mpz.py, test/test_xmpz.py
Before, e.g. for the mpz:
```pycon
>>> import gmpy2
>>> gmpy2.__version__
'2.2.1'
>>> gmpy2.mpz(s=1)
mpz(0)
>>> gmpy2.mpz(1, s=1)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: argument for function given by name ('s') and position (1)
```
=> Correct argument handling for constructors

src/gmpy2_binary.c, src/gmpy2_macros.h, src/gmpy2_mpz_misc.c
It seems, that using mpn_get_str() is more efficient than generic mpz_export().
Some benchmarks are here:
https://github.com/aleaxit/gmpy/issues/404#issuecomment-2526603947
Not sure what else we can do for #404.  In the python-gmp I've added also the `__reduce__` dunded method.  This seems slightly better than rely on copyreg to support pickling:
| Benchmark      | ref     | patch                 | gmp                   |
|----------------|:-------:|:---------------------:|:---------------------:|
| dumps(1<<7)    | 23.9 us | 23.8 us: 1.01x faster | 22.6 us: 1.06x faster |
| dumps(1<<38)   | 24.0 us | 23.9 us: 1.01x faster | 22.7 us: 1.06x faster |
| dumps(1<<300)  | 24.1 us | 23.8 us: 1.01x faster | 22.9 us: 1.05x faster |
| dumps(1<<3000) | 26.8 us | 25.2 us: 1.07x faster | 23.8 us: …
=> Optimize to_binary() function and to_bytes() method

.github/workflows/pip_install_gmpy2.yml, pyproject.toml, src/gmpy2.c, src/gmpy2_binary.c, src/gmpy2_cache.c, src/gmpy2_convert_gmp.c, src/gmpy2_xmpz.c, test/test_misc.py
=> Support PyPy

src/gmpy2_mpz_bitops.c, test/test_mpz.py
=> Avoid OverflowError in mpz.__rshift__()

src/gmpy2_mpz_misc.c, test/test_mpz.py
The GNU GMP manual says that about mpz_sizeinbaze(): "The result will be either exact or 1 too big."  First happened for example in the issue. We should use strict inequality to handle this.
Closes #552
=> Correct optimization for negative ndigits in mpz.__round__()

.github/workflows/build_wheels.yml, docs/overview.rst
closes #529
I'll mark also additional issues (merging this will close them too):
* closes #132 - support for ancient MPFR/MPC
* closes #518 - use abs() in cython
* closes #472 - using gmpy2 C-API
* closes #340 - crash with cached_context (not used anymore)
* closes #128 - compile error for anciend gmpy2-2.0.8 on py2
* closes #102 - compiling ancient 2.0.7 on Windows
* closes #16 - use cython for wrapping.  Nope ;-)
* closes #22 - _mpmath_mpf_mul patch (not accessible)
* closes #95 - setup.py --prefix
* closes #119 - tagging releases
* closes #122 - support for ``__new__``
* closes #146 - release?
* closes #158 - tests with MPIR (not supported)
* closes #176 - refactor build processes (now it much different)
* closes #185 - setuptools issue
* closes #199 - 2.1.0 Beta
* closes #488 - 2.2.0: …
=> Advertise python-gmp ;-)

.github/workflows/build_wheels.yml, .github/workflows/pip_install_gmpy2.yml, scripts/cibw_before_all.sh, scripts/dll-importexport.diff, src/gmpy2.c, src/gmpy2_convert_gmp.c
* skip cache for them
* test in CI
* build wheels
* remove global cache for int's layout
See https://github.com/aleaxit/gmpy/issues/584
=> Implement basic support for the free-threaded build
